"""Standard OpenTelemetry attribute definitions for reasoning-mcp.

This module defines semantic attribute names used across all spans
to ensure consistent naming and easy filtering in observability tools.
"""

from __future__ import annotations

# =============================================================================
# Universal Attributes
# =============================================================================

# Session context
ATTR_SESSION_ID = "session.id"
"""Unique identifier for the reasoning session."""

# Pipeline context
ATTR_PIPELINE_ID = "pipeline.id"
"""Unique identifier for the pipeline execution."""

# Stage context
ATTR_STAGE_ID = "stage.id"
"""Unique identifier for the pipeline stage."""

ATTR_STAGE_TYPE = "stage.type"
"""Type of stage: method, sequence, parallel, loop, conditional, switch."""

ATTR_STAGE_NAME = "stage.name"
"""Human-readable name of the stage."""

# =============================================================================
# Method-specific Attributes
# =============================================================================

ATTR_METHOD_ID = "method.id"
"""Identifier of the reasoning method being executed."""

ATTR_METHOD_TIMEOUT = "method.timeout_seconds"
"""Timeout configured for the method execution."""

ATTR_THOUGHTS_GENERATED = "method.thoughts_generated"
"""Number of thoughts generated by the method."""

ATTR_METHOD_CONFIDENCE = "method.confidence"
"""Confidence score of the method's output (0.0-1.0)."""

ATTR_METHOD_QUALITY = "method.quality_score"
"""Quality score of the method's output."""

# =============================================================================
# Parallel Execution Attributes
# =============================================================================

ATTR_BRANCH_COUNT = "parallel.branch_count"
"""Number of parallel branches being executed."""

ATTR_MAX_CONCURRENCY = "parallel.max_concurrency"
"""Maximum concurrency limit for parallel execution."""

ATTR_MERGE_STRATEGY = "parallel.merge_strategy"
"""Strategy used to merge parallel results."""

ATTR_BRANCH_INDEX = "parallel.branch_index"
"""Index of the current branch (0-based)."""

ATTR_BRANCH_SUCCESS_COUNT = "parallel.success_count"
"""Number of branches that completed successfully."""

ATTR_BRANCH_FAILURE_COUNT = "parallel.failure_count"
"""Number of branches that failed."""

# =============================================================================
# Loop Execution Attributes
# =============================================================================

ATTR_ITERATION = "loop.iteration"
"""Current iteration number (0-based)."""

ATTR_MAX_ITERATIONS = "loop.max_iterations"
"""Maximum number of iterations allowed."""

ATTR_TERMINATION_REASON = "loop.termination_reason"
"""Reason the loop terminated: condition_met, max_iterations, error."""

ATTR_LOOP_CONDITION = "loop.condition"
"""The loop condition expression."""

# =============================================================================
# Conditional Execution Attributes
# =============================================================================

ATTR_CONDITION_EXPRESSION = "conditional.expression"
"""The condition expression being evaluated."""

ATTR_CONDITION_RESULT = "conditional.result"
"""Result of condition evaluation: true or false."""

ATTR_BRANCH_TAKEN = "conditional.branch_taken"
"""Which branch was taken: if_true or if_false."""

# =============================================================================
# Switch Execution Attributes
# =============================================================================

ATTR_SWITCH_EXPRESSION = "switch.expression"
"""The switch expression being evaluated."""

ATTR_SWITCH_VALUE = "switch.value"
"""The evaluated value of the switch expression."""

ATTR_CASE_MATCHED = "switch.case_matched"
"""The case that was matched, or 'default' if no match."""

ATTR_CASE_COUNT = "switch.case_count"
"""Total number of cases in the switch."""

# =============================================================================
# Error Attributes
# =============================================================================

ATTR_ERROR_TYPE = "error.type"
"""Type/class of the error."""

ATTR_ERROR_MESSAGE = "error.message"
"""Error message."""

ATTR_ERROR_STAGE = "error.stage"
"""Stage where the error occurred."""

# =============================================================================
# Performance Attributes
# =============================================================================

ATTR_DURATION_MS = "duration.ms"
"""Duration of the operation in milliseconds."""

ATTR_RETRY_COUNT = "retry.count"
"""Number of retries performed."""

ATTR_RETRY_MAX = "retry.max"
"""Maximum retries allowed."""
